# Generated by Django 5.0.3 on 2024-03-13 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_user_profile_username_alter_rating_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='business',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Type_of_Business',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
